services:
  - type: web
    name: dldm
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn dldm.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DJANGO_SETTINGS_MODULE
        value: dldm.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_ALLOWED_HOSTS
        value: dldm.onrender.com,localhost,127.0.0.1
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: https://dldm.onrender.com,http://dldm.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: dldm-db
          property: connectionString

databases:
  - name: dldm-db
    databaseName: dldm
    user: dldm_user
    plan: free