# Generated by Django 5.2.1 on 2025-06-08 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+255999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'System Admin'), ('STOCK_MANAGER', 'Stock Manager'), ('SALES_MANAGER', 'Sales Manager'), ('COMPANY_MANAGER', 'Company Manager')], default='SYSTEM_ADMIN', max_length=20),
        ),
    ]
