# Generated by Django 5.2.1 on 2026-02-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salesmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='order_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
